// Decisões explícitas conferidas com EXAM_INVENTORY.md e com os HTMLs.
export const phase3Base = 'd029f44501e32f0358160a613ce262379dc26af1';
export interface MigrationEntry {
  id: string;
  sourceFile: string;
  title: string;
  subject: string;
  year: number | null;
  division: string;
  objective: number;
  essay: number;
  classification: string;
  notes: string[];
}
const entry = (
  id: string,
  file: string,
  title: string,
  subject: string,
  year: number | null,
  division: string,
  objective: number,
  essay = 0,
  notes: string[] = [],
  classification = 'objetiva simples; conteúdo rico',
) => ({
  id,
  sourceFile: `simulados/${file}.html`,
  title,
  subject,
  year,
  division,
  objective,
  essay,
  classification,
  notes,
});
export const remainingExams: MigrationEntry[] = [
  entry(
    'farmaco-p2-2023',
    'farmaco-p2-Simulado-2023',
    'Plataforma de Avaliação — Farmacologia',
    'Farmacologia',
    2023,
    'P2',
    35,
    0,
    ['9 questões com quatro alternativas e 26 com cinco.'],
  ),
  entry(
    'farmaco-p2-2024',
    'farmaco-p2-Simulado-2024',
    'Plataforma de Avaliação — Farmacologia',
    'Farmacologia',
    2024,
    'P2',
    34,
    0,
    ['8 questões com quatro alternativas e 26 com cinco.'],
  ),
  entry(
    'farmaco-p2-2025',
    'farmaco-p2-Simulado-2025',
    'Simulado de Farmacologia 2025 — Questões 04 a 45',
    'Farmacologia',
    2025,
    'P2',
    42,
    0,
    [
      'Numeração original 4–45; questões 1–3 ausentes na fonte, sem preenchimento. 36 questões com quatro alternativas e seis com cinco.',
    ],
  ),
  entry(
    'fisiologia-m5-aula-2',
    'fisiologia-aula-m5-2-Hormônios Pancreáticos',
    'Fisiologia dos Hormônios Pancreáticos',
    'Fisiologia',
    2026,
    'M5, aula 2',
    20,
    5,
    [
      'Ano explicitamente declarado no HTML: hub “Edição 2026” (linha 1702) e badge “Fisiologia 2026” (linha 1783). Corrige a observação de ano ausente da auditoria; não inferido da sequência.',
      'Módulos independentes: objetivas seguidas de dissertativas, preservando ordem interna e numeração reiniciada, conforme a decisão da POC.',
    ],
    'mista; conteúdo rico',
  ),
  entry(
    'fisiologia-m5-endocrino-em-grupo-2026',
    'fisiologia-m5-Endocrino em Grupo',
    'Fisiologia 2026 — Endocrinologia Médica',
    'Fisiologia',
    2026,
    'M5, trabalho em grupo',
    0,
    8,
    [
      'Três casos, oito subitens: q1_a–q1_c, q2_a–q2_b, q3_a–q3_c. mainNum integral em label, num em ID composto; caso completo compartilhado em groups e referências de continuação em context.',
      'Preservados literalmente: “somatostatinahipotalâmica”, “endocitose do colo”, testosterona livre 1200 ng/dL versus referência 3,03 – 14,80 ng/dL e paciente/pacienta com identificação variável. Sem revisão ou correção acadêmica.',
    ],
    'dissertativa; caso/subitem; conteúdo rico/tabela',
  ),
  entry(
    'imunologia-b4-2022',
    'imunologia-b4-Simulado 2022',
    'Plataforma de Avaliação — Imunologia Médica',
    'Imunologia',
    2022,
    'B4',
    30,
  ),
  entry(
    'imunologia-b4-2023',
    'imunologia-b4-Simulado 2023',
    'Imunologia Médica P4 (2023)',
    'Imunologia',
    2023,
    'P4',
    30,
    0,
    [
      'Arquivo/catálogo legado B4, título e identificação da prova P4. division P4 segue a identificação explícita da prova; ID conserva origem B4, registrada em sourceFile. Nenhuma questão foi alterada.',
    ],
  ),
  entry(
    'imunologia-b4-2024',
    'imunologia-b4-Simulado 2024',
    'Microbiologia e Virologia — Prova 2024',
    'Microbiologia/Virologia',
    2024,
    'B4',
    30,
    0,
    [
      'Arquivo/catálogo legado Imunologia; título e conteúdo Microbiologia/Virologia. subject segue título/conteúdo, ID conserva identidade do arquivo para distinguir da outra prova Microbiologia 2024. Fonte legada intacta.',
    ],
  ),
  entry(
    'imunologia-b4-2025',
    'imunologia-b4-Simulado 2025',
    'Plataforma de Avaliação — Imunologia Médica',
    'Imunologia',
    2025,
    'B4',
    30,
  ),
  entry(
    'micro-b4-2023',
    'micro-b4-Simulado 2023',
    'Microbiologia e Virologia Clínica',
    'Microbiologia/Virologia',
    2023,
    'B4',
    30,
  ),
  entry(
    'micro-b4-2024',
    'micro-b4-Simulado 2024',
    'Microbiologia e Virologia Clínica',
    'Microbiologia/Virologia',
    2024,
    'B4',
    30,
  ),
  entry(
    'micro-b4-2025',
    'micro-b4-Simulado 2025',
    'Microbiologia e Virologia',
    'Microbiologia/Virologia',
    2025,
    'B4',
    30,
  ),
  entry(
    'parasito-b4-2025',
    'parasito-b4-Simulado 2025',
    'Parasitologia e Dermatozoonoses',
    'Parasitologia',
    2025,
    'B4',
    31,
    0,
    [
      '30 categorias para 31 questões, uma repetida. Bug setItem do motor legado não transportado para dados.',
    ],
  ),
  entry(
    'patologia-b3-2025',
    'patologia-b3-Simulado-2025',
    'Patologia e Imunologia Médica',
    'Patologia/Imunologia',
    2025,
    'B3',
    30,
    0,
    ['Quatro alternativas em cada questão.'],
  ),
  entry(
    'propedeu-p2-2024',
    'propedeu-p2-Simulado 2024',
    'Clínica Médica e Propedêutica',
    'Propedêutica/Clínica Médica',
    2024,
    'P2',
    20,
    0,
    ['Quatro alternativas em cada questão.'],
  ),
  entry(
    'propedeu-p2-2025',
    'propedeu-p2-Simulado 2025',
    'Propedêutica Médica',
    'Propedêutica',
    2025,
    'P2',
    20,
    0,
    ['Quatro alternativas em cada questão; 15 categorias.'],
  ),
];
